add noetic test and also checks python 2/3 compatibility
PR2/app_manager pull request #24
Opened 2020-04-25 09:04 UTC by k-okada

2020-05-01 15:00 UTC, knorth55 requested changes

2020-05-01 15:00 UTC, knorth55 commented on src/app_manager/app_manager.py
> +    import _thread # python3 renamed from thread to _thread
just importing does not seem to solve the problem.
maybe `import _thread as thread`?

2020-05-01 15:01 UTC, knorth55 commented
I think it is better to use `rospy.logerr` and `rospy.loginfo` for logging instead of `print` function.

2020-05-04 08:41 UTC, v4hn reviewed
I would strictly prefer migration to `rospy.log*`.
These scripts were written in early stages of ROS development, and apparently the logging commands were not as established back then.

2020-05-04 08:41 UTC, v4hn commented on src/app_manager/exchange.py
> +from __future__ import print_function
Either you add it to *every* file or you leave it out.

2020-05-04 08:41 UTC, v4hn commented on src/app_manager/master_sync.py
> +    from urllib.parse import urlparse # python3 renamed from thread to _thread
The comment is wrong

2020-07-09 10:42 UTC, v4hn commented
ping @k-okada.

This is still required for noetic.

2020-07-10 09:42 UTC, k-okada commented
Sorry for late, There seems  several place to update (use `rospy.log`, fix comment and so on..) Could @v4hn or @knorth55 create PR for me?

2020-07-10 10:50 UTC, v4hn commented
@knorth55 could you create a follow-up pr to fix this up?

2020-07-10 14:10 UTC, knorth55 commented
@k-okada @v4hn I made a follow-up PR https://github.com/k-okada/app_manager/pull/1

2020-07-13 09:50 UTC, v4hn approved these changes

2020-07-13 09:55 UTC, merged